import type { AssetSupplyContext, MissingMaterialBrief } from '@viral-struct/shared';

export interface ScenarioRun {
  scenario: string;
  context: AssetSupplyContext;
  outputPath: string;
}

export interface ScenarioBenchmarkSummary {
  scenario: string;
  evidenceCoverage: number;
  completionFeasibility: number;
  covered: number;
  weak: number;
  insufficient: number;
  observations: number;
  missingBriefs: number;
  downstreamMode: string;
}

export interface ScenarioReportInputs {
  structureGraph: string;
  originalAssetCards: string;
  plainAssetCards: string;
  aigcSampleDescriptor?: string;
}

export function summarizeScenarioRun(run: ScenarioRun): ScenarioBenchmarkSummary {
  const coverage = run.context.contextualCoverage?.coverageSummary;
  const scenario = run.context.materialScenario;
  return {
    scenario: run.scenario,
    evidenceCoverage: scenario?.evidenceCoverageScore ?? coverage?.coverageScore ?? 0,
    completionFeasibility: scenario?.completionFeasibilityScore ?? 0,
    covered: coverage?.coveredSlots ?? 0,
    weak: coverage?.weakSlots ?? 0,
    insufficient: coverage?.insufficientSlots ?? 0,
    observations: run.context.contextualCoverage?.observations.length ?? 0,
    missingBriefs: run.context.missingMaterialBriefs?.length ?? 0,
    downstreamMode: scenario?.recommendedDownstreamMode ?? 'unknown'
  };
}

export function buildScenarioComparisonReport(runs: ScenarioRun[], inputs: ScenarioReportInputs): string {
  const rows = runs.map(summarizeScenarioRun);

  return `# Asset Manager Scenario Comparison Report

Generated by \`scripts/manual_test_asset_manager_scenarios.ts\`.

## Inputs

- Structure graph: \`${inputs.structureGraph}\`
- Product image library: \`${inputs.originalAssetCards}\`
- Plain user video library: \`${inputs.plainAssetCards}\`
- AIGC planned descriptor source: \`${inputs.aigcSampleDescriptor ?? 'not found'}\` when present

## Scenario Summary

| scenario | evidenceCoverage | completionFeasibility | covered | weak | insufficient | observations | missingBriefs | downstreamMode |
|---|---:|---:|---:|---:|---:|---:|---:|---|
${rows.map((row) => `| ${row.scenario} | ${row.evidenceCoverage} | ${row.completionFeasibility} | ${row.covered} | ${row.weak} | ${row.insufficient} | ${row.observations} | ${row.missingBriefs} | ${row.downstreamMode} |`).join('\n')}

## Per-role Coverage

${runs.map(formatRoleCoverageSection).join('\n\n')}

## Observation Types

${runs.map(formatObservationSection).join('\n\n')}

## Key Missing Material Briefs

${runs.map(formatBriefSection).join('\n\n')}

## Boundary

Asset Manager outputs evidence and handoff briefs only. It does not make final downstream repair decisions, generate real video, or compose MP4.

For the \`aigc_ready\` scenario, generated assets are planned descriptors and prompt briefs only; they are not real rendered output.
`;
}

function formatRoleCoverageSection(run: ScenarioRun): string {
  const roleMap = new Map<string, { covered: number; weak: number; insufficient: number }>();
  for (const row of run.context.contextualCoverage?.slotCoverages ?? []) {
    const bucket = roleMap.get(row.slotRole) ?? { covered: 0, weak: 0, insufficient: 0 };
    bucket[row.coverageStatus] += 1;
    roleMap.set(row.slotRole, bucket);
  }
  const preferredRoles = ['opening_attention', 'product_closeup', 'usage_demo', 'benefit_proof', 'comparison', 'cta_visual', 'cover'];
  const roles = Array.from(new Set([...preferredRoles, ...roleMap.keys()]));
  const lines = roles
    .map((role) => ({ role, values: roleMap.get(role) }))
    .filter((entry) => entry.values)
    .map((entry) => `| ${entry.role} | ${entry.values?.covered ?? 0} | ${entry.values?.weak ?? 0} | ${entry.values?.insufficient ?? 0} |`);
  return `### ${run.scenario}

| role | covered | weak | insufficient |
|---|---:|---:|---:|
${lines.length ? lines.join('\n') : '| none | 0 | 0 | 0 |'}`;
}

function formatObservationSection(run: ScenarioRun): string {
  const counts = new Map<string, number>();
  for (const observation of run.context.contextualCoverage?.observations ?? []) {
    counts.set(observation.observationType, (counts.get(observation.observationType) ?? 0) + 1);
  }
  const lines = Array.from(counts.entries())
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([type, count]) => `- ${type}: ${count}`);
  return `### ${run.scenario}

${lines.length ? lines.join('\n') : 'No weak or insufficient slot observations.'}`;
}

function formatBriefSection(run: ScenarioRun): string {
  const briefs = (run.context.missingMaterialBriefs ?? []).slice(0, 5);
  if (!briefs.length) return `### ${run.scenario}\n\nNo missing material briefs.`;
  return `### ${run.scenario}

${briefs.map(formatBrief).join('\n')}`;
}

function formatBrief(brief: MissingMaterialBrief): string {
  const channels = brief.channelEligibility
    .filter((channel) => channel.eligible)
    .map((channel) => channel.channel)
    .join(', ');
  return `- \`${brief.affectedSlotId}\` (${brief.slotRole}): ${brief.manualShootBrief?.title ?? 'material brief'}; channels=${channels}; prompt=${brief.aigcGenerationBrief?.prompt.slice(0, 120) ?? 'n/a'}...`;
}
